### ISSUE TITLE
ModuleNotFoundError: No module named '_kaldilm'

### ISSUE THREAD

**Issue by aheba** [csukuangfj/kaldilm#1]
Hello @csukuangfj ,
I'm trying to use kaldilm so I create a Conda env with python3.8 + I use the kaldilm 1.2 installed with:
```
(snowfall) aheba@koios:~/snowfall/egs/librispeech/asr/simple_v1$ pip install kaldilm
Collecting kaldilm
  Downloading kaldilm-1.2.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 1.4 MB/s
Building wheels for collected packages: kaldilm
  Building wheel for kaldilm (setup.py) ... done
  Created wheel for kaldilm: filename=kaldilm-1.2-cp38-cp38-linux_x86_64.whl size=16446 sha256=77214d2b8764668407184a5c63b2d6071a2efca0f5c547a0f8c0949e99b56263
  Stored in directory: /home/aheba/.cache/pip/wheels/bd/c9/d9/2ff092ec86b049bb1d551b27e4122bb06ceabfef345180b67e
Successfully built kaldilm
Installing collected packages: kaldilm
Successfully installed kaldilm-1.2
```

And I got this error when I try to call the `apra2fst` function

```
Traceback (most recent call last):
  File "/home/aheba/anaconda3/envs/snowfall/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/aheba/anaconda3/envs/snowfall/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/aheba/anaconda3/envs/snowfall/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/aheba/anaconda3/envs/snowfall/lib/python3.8/site-packages/kaldilm/__init__.py", line 1, in <module>
    from .arpa2fst import arpa2fst
  File "/home/aheba/anaconda3/envs/snowfall/lib/python3.8/site-packages/kaldilm/arpa2fst.py", line 3, in <module>
    import _kaldilm
ModuleNotFoundError: No module named '_kaldilm'
```

**Comment by csukuangfj** [comment]
Thanks for reporting. I am looking into it.

**Comment by csukuangfj** [comment]
@aheba 

Can you check that there is a file with name ` _kaldilm.cpython-38-x86_64-linux-gnu.so`
inside the directory `/home/aheba/anaconda3/envs/snowfall/lib/python3.8/site-packages` ?

I cannot reproduce your problem with miniconda3 on my computer.

**Comment by pehonnet** [comment]
Maybe you are missing `cmake` ...

**Comment by eeewhe** [comment]
version 1.2?

**Comment by aheba** [comment]
hello, thanks for you quick response,
I tired with kaldilm 1.2 & 1.3. same behaviour.

I use a fresh Conda env with:
```
(snowfall) aheba@koios:~/anaconda3$ conda create -n test python=3.8
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/aheba/anaconda3/envs/test

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.8.8               |       hdb3f193_4        50.0 MB
    ------------------------------------------------------------
                                           Total:        50.0 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.1.19-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2020.12.5-py38h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1j-h27cfd23_0
  pip                pkgs/main/linux-64::pip-21.0.1-py38h06a4308_0
  python             pkgs/main/linux-64::python-3.8.8-hdb3f193_4
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py38h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.33.0-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.8.8         | 50.0 MB   | ################################################################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(snowfall) aheba@koios:~/anaconda3$ conda activate test
(test) aheba@koios:~/anaconda3$ pip install kaldilm
Collecting kaldilm
  Using cached kaldilm-1.3-cp38-cp38-linux_x86_64.whl
Installing collected packages: kaldilm
Successfully installed kaldilm-1.3
(test) aheba@koios:~/anaconda3$ python
Python 3.8.8 (default, Feb 24 2021, 21:46:12)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaldilm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aheba/anaconda3/envs/test/lib/python3.8/site-packages/kaldilm/__init__.py", line 1, in <module>
    from .arpa2fst import arpa2fst
  File "/home/aheba/anaconda3/envs/test/lib/python3.8/site-packages/kaldilm/arpa2fst.py", line 3, in <module>
    import _kaldilm
ModuleNotFoundError: No module named '_kaldilm'

```

here is some insights:
```
(test) aheba@koios:~/anaconda3$ ls /home/aheba/anaconda3/envs/test/lib/python3.8/site-packages/
README.txt                                     distutils-precedence.pth                       pip-21.0.1-py3.8.egg-info/                     wheel/
_distutils_hack/                               kaldilm/                                       pkg_resources/                                 wheel-0.36.2-py3.6.egg-info/
certifi/                                       kaldilm-1.3.dist-info/                         setuptools/
certifi-2020.12.5-py3.8.egg-info/              pip/                                           setuptools-52.0.0.post20210125-py3.8.egg-info/
```

and there is no `_kaldilm.cpython-38-x86_64-linux-gnu.so` anywhere in the kaldilm

**Comment by aheba** [comment]
BTW, when I try to install it on other server, it works. but not with my own server.

with another server I found the lib.so in `/users/samova/aheba/.conda/envs/snowfall/lib/python3.8/site-packages/libkaldilm_core.so`

Strange behaviour..

**Comment by eeewhe** [comment]
I clone this project and build. The build/lib folder contains some ".so" files. 
```
mkdir build & cd build
cmake ..
make
```
_kaldilm.cpython-37m-x86_64-linux-gnu.so  libfst.so  libfst.so.16  libkaldilm_core.so
Then, I copy these lib files to temp.linux-x86_64-3.7/lib/, and execute `python setup.py bdist_wheel`, then the wheel file is generated.
It works for me.

**Comment by aheba** [comment]
Hello @hegc,

It work fine for me with that solution.

It would be great if you can add some lines in the readme for `manual install`.

Feel free to close this issue. Thank you guys, let play with snowfall :)

**Comment by csukuangfj** [comment]
@hegc 
Thanks for providing an alternative.

@aheba 

Would you mind providing the log for the following command?

```
pip install -v --no-cache-dir kaldilm
```

It is strange that the installation process on your computer does not work.

**Comment by aheba** [comment]
hello @csukuangfj ,
the installation fail on my new server..
I found the reason, it appear that my server doesn't have essential libs to compile the C++ code... 
So doing:
```
pip install kaldilm
```
fail just before the compilation phase
```
(base) aheba@koios:~$ pip install -v --no-cache-dir kaldilm
Using pip 20.2.4 from /home/aheba/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-92d6oklk
Created temporary directory: /tmp/pip-req-tracker-vxoxv0uf
Initialized build tracking at /tmp/pip-req-tracker-vxoxv0uf
Created build tracker: /tmp/pip-req-tracker-vxoxv0uf
Entered build tracker: /tmp/pip-req-tracker-vxoxv0uf
Created temporary directory: /tmp/pip-install-2xhn0kn3
1 location(s) to search for versions of kaldilm:
* https://pypi.org/simple/kaldilm/
Fetching project page and analyzing links: https://pypi.org/simple/kaldilm/
Getting page https://pypi.org/simple/kaldilm/
Found index url https://pypi.org/simple
Getting credentials from keyring for https://pypi.org/simple
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/kaldilm/ HTTP/1.1" 200 1932
  Found link https://files.pythonhosted.org/packages/fe/43/b10d6736002f218f9a9e9b46c5828ed03790459dd3f704f4fa0c4d5a59ce/kaldilm-0.1.tar.gz#sha256=06e3cbb560a186147664c708e12788f44be4bf36d826b882e6c1a0865e2141c5 (from https://pypi.org/simple/kaldilm/), version: 0.1
  Found link https://files.pythonhosted.org/packages/30/aa/e64bb80ed5c389cb7e4dc64784d3cac29379f00e0e287b7b993fa7d48348/kaldilm-0.2.tar.gz#sha256=74d94fdc08f14bf49590a4875e139c474c62badb38319a112a40bcb6fb528488 (from https://pypi.org/simple/kaldilm/), version: 0.2
  Found link https://files.pythonhosted.org/packages/3a/ac/e9441411b4c6355ea23c716075946d9cb3a9d515d3e0d4b170cb832745ac/kaldilm-0.2.1.tar.gz#sha256=4c0d4065a86672e93554abac8f9c7c3a1bc64b8308133d70908820618c0541ca (from https://pypi.org/simple/kaldilm/), version: 0.2.1
  Found link https://files.pythonhosted.org/packages/e1/0e/93d28c24e406cb9b17a27a831ca47e5b401a98ffcf03869c12aa4e64ddcd/kaldilm-0.2.2.tar.gz#sha256=a336b2a3504458cf9a43ef69a3caa109927bafc9c136db0ba1a1697f53010021 (from https://pypi.org/simple/kaldilm/), version: 0.2.2
  Found link https://files.pythonhosted.org/packages/da/e8/1c5b34c6480d186fc0e7277a8b9a3cd47220945a6e0a8e50c5a50fb3fa5d/kaldilm-0.2.3.tar.gz#sha256=e33257eb9937e896b954888a4da8d4cfaac3aabeebfa41d40c905d168961557a (from https://pypi.org/simple/kaldilm/), version: 0.2.3
  Found link https://files.pythonhosted.org/packages/d9/bd/495a848be11da97a90c7fead0a5a68d5c5bfcd2c2f2dd614a6b6ad17d149/kaldilm-0.2.4.tar.gz#sha256=73a1998b44c5da833a358328f0a370353aac042bdd0cf75c7e92bef16581886c (from https://pypi.org/simple/kaldilm/), version: 0.2.4
  Found link https://files.pythonhosted.org/packages/17/4a/d32f68371432c257605675c8058288f3aad3c22798a321cacb65f5a85f11/kaldilm-0.2.5.tar.gz#sha256=8d186e71c095e48b50b09df5f2963aa7d685646d033e0da8b4bbf66e7bed1f3f (from https://pypi.org/simple/kaldilm/), version: 0.2.5
  Found link https://files.pythonhosted.org/packages/d3/d5/817b2af718bbab08dcaedaaaf9e6fc1ba0b927f0b449d46aea3f12ed4e79/kaldilm-0.3.0.tar.gz#sha256=f2c14b345fd9003f3eec88aceb71c019b900c80b441527224b7b717d03357954 (from https://pypi.org/simple/kaldilm/), version: 0.3.0
  Found link https://files.pythonhosted.org/packages/91/45/c13a76d84f07829969edb2f1be92f1d6975efd1faa76e98a0aeb8027db66/kaldilm-0.3.2.tar.gz#sha256=9471eb9f255716ed5540ef5be8621cbb019db06ea7773d671f6562ada9cc094f (from https://pypi.org/simple/kaldilm/), version: 0.3.2
  Found link https://files.pythonhosted.org/packages/ed/77/7f9eebcb5a37e0f9626c3efad5059a1a2287444371de08bc4b70399fe76c/kaldilm-0.3.3.tar.gz#sha256=8fc9acdde850a2a9756ac8e7383e230e3d84401cb20555d51cdea83c02605d50 (from https://pypi.org/simple/kaldilm/), version: 0.3.3
  Found link https://files.pythonhosted.org/packages/5a/93/8a93ce728eeb805edc695742a404bdfa71c11507be58e7bb6fb961fba15e/kaldilm-0.3.4.tar.gz#sha256=0fcd0e445d60b4efa6a4a139dec741774021c31d844c63d304ac3286f077e25b (from https://pypi.org/simple/kaldilm/), version: 0.3.4
  Found link https://files.pythonhosted.org/packages/e8/57/7e18fc42536b1c228b6f28eb6e1348927c8c92e3bb7f8b69bc5e3c692593/kaldilm-1.0.tar.gz#sha256=3a22730a8ef6fb4c883a2b36b84c726ac805424ecd9ad67b7e5af8acdf031510 (from https://pypi.org/simple/kaldilm/), version: 1.0
  Found link https://files.pythonhosted.org/packages/58/04/72b3d64add893ae562c079085dfa5a96a9dc74b67f4d045e587c6730a9d2/kaldilm-1.0.1.tar.gz#sha256=26bc8330b04b91f86b56873fcce071b6d2bf2adaa02f65e949ae856a3a234b85 (from https://pypi.org/simple/kaldilm/), version: 1.0.1
  Found link https://files.pythonhosted.org/packages/d3/48/f280354f2bee54fffd3a19916c00262539266a8832ad15562e6d464a2d67/kaldilm-1.0.2.tar.gz#sha256=90381b880bc2c9a668ae4bc6dec6d7dcf5b51dc90d1f2d9c680976bc21cdf56b (from https://pypi.org/simple/kaldilm/), version: 1.0.2
  Found link https://files.pythonhosted.org/packages/99/db/84ed6ba85cddac4a3655d21ac9cbdc70f9a7cbd6a3b45189034a77dd7f3c/kaldilm-1.0.3.tar.gz#sha256=be2adb4dbda8b52b9eab0e0d8458a676b74c6ec5997eff12bac0ef3801721dd9 (from https://pypi.org/simple/kaldilm/), version: 1.0.3
  Found link https://files.pythonhosted.org/packages/ed/37/ca706cfc68b2ebc82df38413f5eeb4537058269f2cecad59d77f39e63d10/kaldilm-1.0.4.tar.gz#sha256=8c7a89bbfee99f843f9f594c78075b22df5d580446b8548e9e9bd79383847d18 (from https://pypi.org/simple/kaldilm/), version: 1.0.4
  Found link https://files.pythonhosted.org/packages/d0/e4/ab8e4ccfabde945865f02ba3a6626581cb1d788fa6e2e904deb610a8bb1a/kaldilm-1.1.tar.gz#sha256=241a3e4385664c3dd489b1c8fa69c55287e2ce61f2bc09818cafccaf16c488c2 (from https://pypi.org/simple/kaldilm/), version: 1.1
  Found link https://files.pythonhosted.org/packages/c7/19/73d55f5d59d7b24ea6e32e380e169c5b6e562e8d9fcea70a8221641017b5/kaldilm-1.2.tar.gz#sha256=219a3c1c8268b444e390ac283a7c78efe20206a55d6ce0aa279af1eb66ba7023 (from https://pypi.org/simple/kaldilm/), version: 1.2
  Found link https://files.pythonhosted.org/packages/e5/cc/01ca439d7be68f84bffa0eb3efebb61340febc4ff8349f1676a97cd1fb7e/kaldilm-1.3.tar.gz#sha256=8ad0f76e5a880b43769674b0ffe9878cf68aac6d4cc43ea95b26fddc34b0a0b5 (from https://pypi.org/simple/kaldilm/), version: 1.3
Given no hashes to check 19 links for project 'kaldilm': discarding no candidates
Using version 1.3 (newest of versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.2, 0.3.3, 0.3.4, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1, 1.2, 1.3)
Collecting kaldilm
  Created temporary directory: /tmp/pip-unpack-c2twobkm
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/e5/cc/01ca439d7be68f84bffa0eb3efebb61340febc4ff8349f1676a97cd1fb7e/kaldilm-1.3.tar.gz HTTP/1.1" 200 45932
  Downloading kaldilm-1.3.tar.gz (45 kB)
     |████████████████████████████████| 45 kB 2.5 MB/s
  Added kaldilm from https://files.pythonhosted.org/packages/e5/cc/01ca439d7be68f84bffa0eb3efebb61340febc4ff8349f1676a97cd1fb7e/kaldilm-1.3.tar.gz#sha256=8ad0f76e5a880b43769674b0ffe9878cf68aac6d4cc43ea95b26fddc34b0a0b5 to build tracker '/tmp/pip-req-tracker-vxoxv0uf'
    Running setup.py (path:/tmp/pip-install-2xhn0kn3/kaldilm/setup.py) egg_info for package kaldilm
    Created temporary directory: /tmp/pip-pip-egg-info-xf4sp0k8
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-xf4sp0k8/kaldilm.egg-info
    writing /tmp/pip-pip-egg-info-xf4sp0k8/kaldilm.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-xf4sp0k8/kaldilm.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-xf4sp0k8/kaldilm.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-xf4sp0k8/kaldilm.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-xf4sp0k8/kaldilm.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file '/tmp/pip-pip-egg-info-xf4sp0k8/kaldilm.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-2xhn0kn3/kaldilm has version 1.3, which satisfies requirement kaldilm from https://files.pythonhosted.org/packages/e5/cc/01ca439d7be68f84bffa0eb3efebb61340febc4ff8349f1676a97cd1fb7e/kaldilm-1.3.tar.gz#sha256=8ad0f76e5a880b43769674b0ffe9878cf68aac6d4cc43ea95b26fddc34b0a0b5
  Removed kaldilm from https://files.pythonhosted.org/packages/e5/cc/01ca439d7be68f84bffa0eb3efebb61340febc4ff8349f1676a97cd1fb7e/kaldilm-1.3.tar.gz#sha256=8ad0f76e5a880b43769674b0ffe9878cf68aac6d4cc43ea95b26fddc34b0a0b5 from build tracker '/tmp/pip-req-tracker-vxoxv0uf'
Building wheels for collected packages: kaldilm
  Created temporary directory: /tmp/pip-wheel-klyc34aj
  Building wheel for kaldilm (setup.py) ...   Destination directory: /tmp/pip-wheel-klyc34aj
  Running command /home/aheba/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2xhn0kn3/kaldilm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2xhn0kn3/kaldilm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-klyc34aj
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/__main__.py -> build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/__init__.py -> build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/arpa2fst.py -> build/lib.linux-x86_64-3.8/kaldilm
  running build_ext
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- No CMAKE_BUILD_TYPE given, default to Release
  -- C++ Standard version: 11
  -- Downloading pybind11
  -- pybind11 is downloaded to /tmp/pip-install-2xhn0kn3/kaldilm/build/temp.linux-x86_64-3.8/_deps/pybind11-src
  -- pybind11 v2.6.0
  -- Found PythonInterp: /home/aheba/anaconda3/bin/python (found version "3.8.5")
  -- Found PythonLibs: /home/aheba/anaconda3/lib/libpython3.8.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Downloading openfst
  -- openfst is downloaded to /tmp/pip-install-2xhn0kn3/kaldilm/build/temp.linux-x86_64-3.8/_deps/openfst-src
  -- The following ICU libraries were not found:
  --   data (required)
  --   i18n (required)
  --   io (required)
  --   test (required)
  --   tu (required)
  --   uc (required)
  -- Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND)
  -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
  -- Configuring done
  -- Generating done
```

and nothing after... It was an issue with missing libs in my new server, I think some essential libs wasn't installed. after installing `python-dev build-essential` libs on my server (outside conda env), the compilation work perfectly...
