### ISSUE TITLE
"pip3 install kaldilm" in Ubuntu18.04 get error

### ISSUE THREAD

**Issue by YanyuanAI** [csukuangfj/kaldilm#10]
Collecting kaldilm
  2 location(s) to search for versions of kaldilm:
  * https://pypi.python.org/simple/kaldilm/
  * https://pypi.python.org/simple/kaldilm/
  Getting page https://pypi.python.org/simple/kaldilm/
  Starting new HTTPS connection (1): pypi.python.org
  https://pypi.python.org:443 "GET /simple/kaldilm/ HTTP/1.1" 301 122
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/kaldilm/ HTTP/1.1" 200 2377
  Analyzing links from page https://pypi.org/simple/kaldilm/
    Found link https://files.pythonhosted.org/packages/fe/43/b10d6736002f218f9a9e9b46c5828ed03790459dd3f704f4fa0c4d5a59ce/kaldilm-0.1.tar.gz#sha256=06e3cbb560a186147664c708e12788f44be4bf36d826b882e6c1a0865e2141c5 (from https://pypi.org/simple/kaldilm/), version: 0.1
    Found link https://files.pythonhosted.org/packages/30/aa/e64bb80ed5c389cb7e4dc64784d3cac29379f00e0e287b7b993fa7d48348/kaldilm-0.2.tar.gz#sha256=74d94fdc08f14bf49590a4875e139c474c62badb38319a112a40bcb6fb528488 (from https://pypi.org/simple/kaldilm/), version: 0.2
    Found link https://files.pythonhosted.org/packages/3a/ac/e9441411b4c6355ea23c716075946d9cb3a9d515d3e0d4b170cb832745ac/kaldilm-0.2.1.tar.gz#sha256=4c0d4065a86672e93554abac8f9c7c3a1bc64b8308133d70908820618c0541ca (from https://pypi.org/simple/kaldilm/), version: 0.2.1
    Found link https://files.pythonhosted.org/packages/e1/0e/93d28c24e406cb9b17a27a831ca47e5b401a98ffcf03869c12aa4e64ddcd/kaldilm-0.2.2.tar.gz#sha256=a336b2a3504458cf9a43ef69a3caa109927bafc9c136db0ba1a1697f53010021 (from https://pypi.org/simple/kaldilm/), version: 0.2.2
    Found link https://files.pythonhosted.org/packages/da/e8/1c5b34c6480d186fc0e7277a8b9a3cd47220945a6e0a8e50c5a50fb3fa5d/kaldilm-0.2.3.tar.gz#sha256=e33257eb9937e896b954888a4da8d4cfaac3aabeebfa41d40c905d168961557a (from https://pypi.org/simple/kaldilm/), version: 0.2.3
    Found link https://files.pythonhosted.org/packages/d9/bd/495a848be11da97a90c7fead0a5a68d5c5bfcd2c2f2dd614a6b6ad17d149/kaldilm-0.2.4.tar.gz#sha256=73a1998b44c5da833a358328f0a370353aac042bdd0cf75c7e92bef16581886c (from https://pypi.org/simple/kaldilm/), version: 0.2.4
    Found link https://files.pythonhosted.org/packages/17/4a/d32f68371432c257605675c8058288f3aad3c22798a321cacb65f5a85f11/kaldilm-0.2.5.tar.gz#sha256=8d186e71c095e48b50b09df5f2963aa7d685646d033e0da8b4bbf66e7bed1f3f (from https://pypi.org/simple/kaldilm/), version: 0.2.5
    Found link https://files.pythonhosted.org/packages/d3/d5/817b2af718bbab08dcaedaaaf9e6fc1ba0b927f0b449d46aea3f12ed4e79/kaldilm-0.3.0.tar.gz#sha256=f2c14b345fd9003f3eec88aceb71c019b900c80b441527224b7b717d03357954 (from https://pypi.org/simple/kaldilm/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/91/45/c13a76d84f07829969edb2f1be92f1d6975efd1faa76e98a0aeb8027db66/kaldilm-0.3.2.tar.gz#sha256=9471eb9f255716ed5540ef5be8621cbb019db06ea7773d671f6562ada9cc094f (from https://pypi.org/simple/kaldilm/), version: 0.3.2
    Found link https://files.pythonhosted.org/packages/ed/77/7f9eebcb5a37e0f9626c3efad5059a1a2287444371de08bc4b70399fe76c/kaldilm-0.3.3.tar.gz#sha256=8fc9acdde850a2a9756ac8e7383e230e3d84401cb20555d51cdea83c02605d50 (from https://pypi.org/simple/kaldilm/), version: 0.3.3
    Found link https://files.pythonhosted.org/packages/5a/93/8a93ce728eeb805edc695742a404bdfa71c11507be58e7bb6fb961fba15e/kaldilm-0.3.4.tar.gz#sha256=0fcd0e445d60b4efa6a4a139dec741774021c31d844c63d304ac3286f077e25b (from https://pypi.org/simple/kaldilm/), version: 0.3.4
    Found link https://files.pythonhosted.org/packages/e8/57/7e18fc42536b1c228b6f28eb6e1348927c8c92e3bb7f8b69bc5e3c692593/kaldilm-1.0.tar.gz#sha256=3a22730a8ef6fb4c883a2b36b84c726ac805424ecd9ad67b7e5af8acdf031510 (from https://pypi.org/simple/kaldilm/), version: 1.0
    Found link https://files.pythonhosted.org/packages/58/04/72b3d64add893ae562c079085dfa5a96a9dc74b67f4d045e587c6730a9d2/kaldilm-1.0.1.tar.gz#sha256=26bc8330b04b91f86b56873fcce071b6d2bf2adaa02f65e949ae856a3a234b85 (from https://pypi.org/simple/kaldilm/), version: 1.0.1
    Found link https://files.pythonhosted.org/packages/d3/48/f280354f2bee54fffd3a19916c00262539266a8832ad15562e6d464a2d67/kaldilm-1.0.2.tar.gz#sha256=90381b880bc2c9a668ae4bc6dec6d7dcf5b51dc90d1f2d9c680976bc21cdf56b (from https://pypi.org/simple/kaldilm/), version: 1.0.2
    Found link https://files.pythonhosted.org/packages/99/db/84ed6ba85cddac4a3655d21ac9cbdc70f9a7cbd6a3b45189034a77dd7f3c/kaldilm-1.0.3.tar.gz#sha256=be2adb4dbda8b52b9eab0e0d8458a676b74c6ec5997eff12bac0ef3801721dd9 (from https://pypi.org/simple/kaldilm/), version: 1.0.3
    Found link https://files.pythonhosted.org/packages/ed/37/ca706cfc68b2ebc82df38413f5eeb4537058269f2cecad59d77f39e63d10/kaldilm-1.0.4.tar.gz#sha256=8c7a89bbfee99f843f9f594c78075b22df5d580446b8548e9e9bd79383847d18 (from https://pypi.org/simple/kaldilm/), version: 1.0.4
    Found link https://files.pythonhosted.org/packages/d0/e4/ab8e4ccfabde945865f02ba3a6626581cb1d788fa6e2e904deb610a8bb1a/kaldilm-1.1.tar.gz#sha256=241a3e4385664c3dd489b1c8fa69c55287e2ce61f2bc09818cafccaf16c488c2 (from https://pypi.org/simple/kaldilm/), version: 1.1
    Found link https://files.pythonhosted.org/packages/c7/19/73d55f5d59d7b24ea6e32e380e169c5b6e562e8d9fcea70a8221641017b5/kaldilm-1.2.tar.gz#sha256=219a3c1c8268b444e390ac283a7c78efe20206a55d6ce0aa279af1eb66ba7023 (from https://pypi.org/simple/kaldilm/), version: 1.2
    Found link https://files.pythonhosted.org/packages/e5/cc/01ca439d7be68f84bffa0eb3efebb61340febc4ff8349f1676a97cd1fb7e/kaldilm-1.3.tar.gz#sha256=8ad0f76e5a880b43769674b0ffe9878cf68aac6d4cc43ea95b26fddc34b0a0b5 (from https://pypi.org/simple/kaldilm/), version: 1.3
    Found link https://files.pythonhosted.org/packages/5d/f3/121362d68a1e1f17ade48586e848a14ce3d3e46fba065479fc1043d47fcd/kaldilm-1.4.tar.gz#sha256=a7402288c20353bebfd5b1c7e254af5c9bcee38726914e922dd4fcada3568591 (from https://pypi.org/simple/kaldilm/), version: 1.4
    Found link https://files.pythonhosted.org/packages/34/90/7ad17c10906fac8b54a70f066407f171bdb26e9b03d187b8ab4cd4b432fc/kaldilm-1.5.tar.gz#sha256=c8dc386d45cf5017da49e589407c0440098168b9acff12d788c872d81f165fe6 (from https://pypi.org/simple/kaldilm/), version: 1.5
    Found link https://files.pythonhosted.org/packages/ba/3c/e978c2f4e4eb3bef5730c75f51f78273045d3075b9f5522bee39bec377ba/kaldilm-1.6.tar.gz#sha256=1654a0d67b54e28588a720ec6b39eabbd51b2a32da83e0dd4d4a59290d0aad5b (from https://pypi.org/simple/kaldilm/), version: 1.6
    Found link https://files.pythonhosted.org/packages/b7/4c/d3452a8d4d970d04ad3441ac33a218270bec6d37b17d639856278946c297/kaldilm-1.7.tar.gz#sha256=87da22b8940203d70c10f0a753d7968f16099aeeca2c014efd39924e53e078e8 (from https://pypi.org/simple/kaldilm/), version: 1.7
    Found link https://files.pythonhosted.org/packages/62/ea/e8fb7cbf628d18c061c7aed7bafe3aa3a7052caf56bb3cdaae62cb592ae1/kaldilm-1.8.tar.gz#sha256=3343afe044d150ab60f8694a8b5426edfe3290e074515db034faf08420b48624 (from https://pypi.org/simple/kaldilm/), version: 1.8
  Using version 1.8 (newest of versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.2, 0.3.3, 0.3.4, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8)
  Starting new HTTPS connection (1): files.pythonhosted.org
  https://files.pythonhosted.org:443 "GET /packages/62/ea/e8fb7cbf628d18c061c7aed7bafe3aa3a7052caf56bb3cdaae62cb592ae1/kaldilm-1.8.tar.gz HTTP/1.1" 200 48798
  Downloading https://files.pythonhosted.org/packages/62/ea/e8fb7cbf628d18c061c7aed7bafe3aa3a7052caf56bb3cdaae62cb592ae1/kaldilm-1.8.tar.gz (48kB)
  Downloading from URL https://files.pythonhosted.org/packages/62/ea/e8fb7cbf628d18c061c7aed7bafe3aa3a7052caf56bb3cdaae62cb592ae1/kaldilm-1.8.tar.gz#sha256=3343afe044d150ab60f8694a8b5426edfe3290e074515db034faf08420b48624 (from https://pypi.org/simple/kaldilm/)
  Running setup.py (path:/tmp/pip-build-fwf2p67y/kaldilm/setup.py) egg_info for package kaldilm
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/kaldilm.egg-info
    writing pip-egg-info/kaldilm.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/kaldilm.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/kaldilm.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/kaldilm.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/kaldilm.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file 'pip-egg-info/kaldilm.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-fwf2p67y/kaldilm has version 1.8, which satisfies requirement kaldilm from https://files.pythonhosted.org/packages/62/ea/e8fb7cbf628d18c061c7aed7bafe3aa3a7052caf56bb3cdaae62cb592ae1/kaldilm-1.8.tar.gz#sha256=3343afe044d150ab60f8694a8b5426edfe3290e074515db034faf08420b48624
Installing collected packages: kaldilm
  Running setup.py install for kaldilm: started
    Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fwf2p67y/kaldilm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mx8i2np3-record/install-record.txt --single-version-externally-managed --compile --user --prefix=
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/kaldilm
    copying kaldilm/python/kaldilm/arpa2fst.py -> build/lib.linux-x86_64-3.6/kaldilm
    copying kaldilm/python/kaldilm/__init__.py -> build/lib.linux-x86_64-3.6/kaldilm
    copying kaldilm/python/kaldilm/__main__.py -> build/lib.linux-x86_64-3.6/kaldilm
    running build_ext
    -- The C compiler identification is GNU 7.4.0
    -- The CXX compiler identification is GNU 7.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc - works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ - works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- No CMAKE_BUILD_TYPE given, default to Release
    -- C++ Standard version: 11
    -- Downloading pybind11
    Scanning dependencies of target pybind11-populate
    [ 11%] Creating directories for 'pybind11-populate'
    [ 22%] Performing download step (download, verify and extract) for 'pybind11-populate'
    -- Downloading...
       dst='/tmp/pip-build-fwf2p67y/kaldilm/build/temp.linux-x86_64-3.6/_deps/pybind11-subbuild/pybind11-populate-prefix/src/v2.6.0.tar.gz'
       timeout='none'
    -- Using src='https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz'
    -- Retrying...
    -- Using src='https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz'
    -- Retry after 5 seconds (attempt #2) ...
    -- Using src='https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz'
    -- Retry after 5 seconds (attempt #3) ...
    -- Using src='https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz'
    -- Retry after 15 seconds (attempt #4) ...
    -- Using src='https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz'
    -- Retry after 60 seconds (attempt #5) ...
    -- Using src='https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz'
    CMake Error at pybind11-subbuild/pybind11-populate-prefix/src/pybind11-populate-stamp/download-pybind11-populate.cmake:159 (message):
      Each download failed!

        error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl

      Closing connection -1

             --- LOG END ---
             error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl

      Closing connection -1

             --- LOG END ---
             error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl

      Closing connection -1

             --- LOG END ---
             error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl

      Closing connection -1

             --- LOG END ---
             error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl

      Closing connection -1

             --- LOG END ---
             error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl

      Closing connection -1

             --- LOG END ---

    CMakeFiles/pybind11-populate.dir/build.make:111: recipe for target 'pybind11-populate-prefix/src/pybind11-populate-stamp/pybind11-populate-download' failed
    make[2]: *** [pybind11-populate-prefix/src/pybind11-populate-stamp/pybind11-populate-download] Error 1
    CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/pybind11-populate.dir/all' failed
    make[1]: *** [CMakeFiles/pybind11-populate.dir/all] Error 2
    Makefile:103: recipe for target 'all' failed
    make: *** [all] Error 2

    CMake Error at cmake/Modules/FetchContent.cmake:798 (message):
      Build step for pybind11 failed: 2
    Call Stack (most recent call first):
      cmake/Modules/FetchContent.cmake:889 (__FetchContent_directPopulate)
      cmake/pybind11.cmake:27 (FetchContent_Populate)
      cmake/pybind11.cmake:33 (download_pybind11)
      CMakeLists.txt:32 (include)

    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-fwf2p67y/kaldilm/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    make: *** No rule to make target '_kaldilm'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fwf2p67y/kaldilm/setup.py", line 81, in <module>
        license='Apache licensed, as found in the LICENSE file',
      File "/home/xudongz/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xudongz/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xudongz/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-fwf2p67y/kaldilm/setup.py", line 33, in build_extension
        '\nBuild kaldilm failed. Please check the error message.\n'
    Exception:
    Build kaldilm failed. Please check the error message.
    You can ask for help by creating an issue on GitHub.

    Click:
        https://github.com/csukuangfj/kaldilm/issues/new

    Running setup.py install for kaldilm: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-build-fwf2p67y/kaldilm
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fwf2p67y/kaldilm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mx8i2np3-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-fwf2p67y/kaldilm/

**Comment by csukuangfj** [comment]
@YanyuanAI 
Could you refer to https://github.com/ethz-asl/gflags_catkin/issues/15 ?

From your error log:
```
     --- LOG END ---
     error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed
     status_code: 1
     status_string: "Unsupported protocol"
     log:
     --- LOG BEGIN ---
     Protocol "https" not supported or disabled in libcurl
```

There are some problems with your installation `curl` or your CMake is linked to a non-SSL capable version of curl.

**Comment by YanyuanAI** [comment]
Hi，
&nbsp; &nbsp;thanks a lot for get in touch with me so fast, I will try this solution.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csukuangfj/kaldilm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csukuangfj/kaldilm] "pip3 install kaldilm" in Ubuntu18.04 get error (#10)





 
@YanyuanAI
 Could you refer to ethz-asl/gflags_catkin#15 ?
 
From your error log:
      --- LOG END ---      error: downloading 'https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz' failed      status_code: 1      status_string: "Unsupported protocol"      log:      --- LOG BEGIN ---      Protocol "https" not supported or disabled in libcurl  
There are some problems with your installation curl or your CMake is linked to a non-SSL capable version of curl.
