### ISSUE TITLE
Import error: _kaldilm

### ISSUE THREAD

**Issue by pzelasko** [csukuangfj/kaldilm#2]
After running `pip install kaldilm`, and running stage 4 in snowfall's run.sh, I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/hltcoe/pzelasko/miniconda3/envs/k2env/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/hltcoe/pzelasko/miniconda3/envs/k2env/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/hltcoe/pzelasko/miniconda3/envs/k2env/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/hltcoe/pzelasko/miniconda3/envs/k2env/lib/python3.7/site-packages/kaldilm/__init__.py", line 1, in <module>
    from .arpa2fst import arpa2fst
  File "/home/hltcoe/pzelasko/miniconda3/envs/k2env/lib/python3.7/site-packages/kaldilm/arpa2fst.py", line 3, in <module>
    import _kaldilm
ModuleNotFoundError: No module named '_kaldilm'
```

The `kaldilm` version is 1.3, python 3.7.9, the system is either CentOS or RHEL (not sure).

**Comment by pzelasko** [comment]
OK I've just found the other issue (#1). I think I can debug it myself.
