### ISSUE TITLE
kaldilm 

### ISSUE THREAD

**Issue by wwfcnu** [csukuangfj/kaldilm#28]
运行python3 -m kaldilm \
    --read-symbol-table="./words.txt" \
    --disambig-symbol='#0' \
    ./input.arpa > G_fst.txt报错
Traceback (most recent call last):                                                                                                                      
  File "tools/k2/icefall/egs/aishell/ASR/local/compile_hlg.py", line 166, in <module>                                                                   
    main()                                                                                                                                              
  File "tools/k2/icefall/egs/aishell/ASR/local/compile_hlg.py", line 156, in main                                                                       
    HLG = compile_HLG(lang_dir, args.lm)                                                                                                                
  File "tools/k2/icefall/egs/aishell/ASR/local/compile_hlg.py", line 71, in compile_HLG                                                                 
    lexicon = Lexicon(lang_dir)                                                                                                                         
  File "/home/tangshuai/repository/wenet/tools/k2/icefall/icefall/lexicon.py", line 165, in __init__                                                    
    self.word_table = k2.SymbolTable.from_file(lang_dir / "words.txt")                                                                                  
  File "/usr/local/python3.7.10/lib/python3.7/site-packages/k2/symbol_table.py", line 131, in from_file                                                 
    return SymbolTable.from_str(f.read().strip())                                                                                                       
  File "/usr/local/python3.7.10/lib/python3.7/site-packages/k2/symbol_table.py", line 97, in from_str                                                   
    f'Expect a line with 2 fields. Given: {len(fields)}'                                                                                                
AssertionError: Expect a line with 2 fields. Given: 1

**Comment by csukuangfj** [comment]
你看下你的words.txt, 是否有一行，只有一列？

**Comment by wwfcnu** [comment]
> 你看下你的words.txt, 是否有一行，只有一列？

**Comment by csukuangfj** [comment]
找到原因了吗

**Comment by wwfcnu** [comment]
感谢，已经解决了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Fangjun ***@***.***> |
| 日期 | 2023年02月06日 10:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [csukuangfj/kaldilm] kaldilm (Issue #28) |

找到原因了吗
