### ISSUE TITLE
Error when installing kaldilm for windows

### ISSUE THREAD

**Issue by luomingshuang** [csukuangfj/kaldilm#9]
(lms-python) PS C:\Users\Luo Mingshuang\Desktop\github-codes\kaldilm> python .\setup.py install
running install
running bdist_egg
running egg_info
writing kaldilm.egg-info\PKG-INFO
writing dependency_links to kaldilm.egg-info\dependency_links.txt
writing top-level names to kaldilm.egg-info\top_level.txt
reading manifest file 'kaldilm.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'kaldilm.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
文件名、目录名或卷标语法不正确。
Traceback (most recent call last):
  File ".\setup.py", line 60, in <module>
    setuptools.setup(
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Anaconda3\envs\lms-python\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File ".\setup.py", line 32, in build_extension
    raise Exception(
Exception:
Build kaldilm failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

**Comment by shushanxingzhe** [comment]
@csukuangfj This cannot install on Windows. Please make it can be installed on Windows. Very thanks.

**Comment by csukuangfj** [comment]
Can you try 
```bash
git clone https://github.com/csukuangfj/kaldilm.git
cd kaldilm
git checkout fix-windows
python3 setup.py install
```

If it fails, please attach the error logs. Thanks!

**Comment by shushanxingzhe** [comment]
**@csukuangfj Very thanks for you kindly reply.
It is still with some error:**

(k2) D:\project\kaldilm>git checkout fix-windows
Switched to a new branch 'fix-windows'
Branch 'fix-windows' set up to track remote branch 'fix-windows' from 'origin'.

(k2) D:\project\kaldilm>python setup.py install
running install
running bdist_egg
running egg_info
creating kaldilm.egg-info
writing kaldilm.egg-info\PKG-INFO
writing dependency_links to kaldilm.egg-info\dependency_links.txt
writing top-level names to kaldilm.egg-info\top_level.txt
writing manifest file 'kaldilm.egg-info\SOURCES.txt'
reading manifest file 'kaldilm.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'kaldilm.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.8
creating build\lib.win-amd64-3.8\kaldilm
copying kaldilm\python\kaldilm\arpa2fst.py -> build\lib.win-amd64-3.8\kaldilm
copying kaldilm\python\kaldilm\__init__.py -> build\lib.win-amd64-3.8\kaldilm
copying kaldilm\python\kaldilm\__main__.py -> build\lib.win-amd64-3.8\kaldilm
running build_ext
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    setuptools.setup(
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\Miniconda\envs\k2\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Miniconda\envs\k2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\Miniconda\envs\k2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Miniconda\envs\k2\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Miniconda\envs\k2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\Miniconda\envs\k2\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\Miniconda\envs\k2\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\Miniconda\envs\k2\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 58, in build_extension
    cmake {cmake_args} -B {self.build_temp} -S {cur_dir}
NameError: name 'cmake_args' is not defined

**Comment by csukuangfj** [comment]
Could you try the following again
```python
cd kaldilm
git pull
python3 setup.py install
```

**Comment by shushanxingzhe** [comment]
Another error come up.

D:\project\kaldilm\build\temp.win-amd64-3.8\Release\_deps\openfst-src\src\include\fst/dfs-visit.h(68): message : 参见“fst
::internal::DfsState<FST>::operator new”的声明 [D:\project\kaldilm\build\temp.win-amd64-3.8\Release\kaldilm\python\csrc\_k
aldilm.vcxproj]
          with
          [
              FST=fst::Fst<fst::StdArc>
          ]
LINK : fatal error LNK1181: 无法打开输入文件“..\..\..\lib\Release\kaldilm_core.lib” [D:\project\kaldilm\build\temp.win-amd64-3.
8\Release\kaldilm\python\csrc\_kaldilm.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    setuptools.setup(
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\Miniconda\envs\k2\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Miniconda\envs\k2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\Miniconda\envs\k2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Miniconda\envs\k2\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Miniconda\envs\k2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Miniconda\envs\k2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Miniconda\envs\k2\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\Miniconda\envs\k2\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\Miniconda\envs\k2\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\Miniconda\envs\k2\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 70, in build_extension
    raise Exception("Failed to build kaldilm")
Exception: Failed to build kaldilm

**Comment by csukuangfj** [comment]
> Another error come up.

I will try to find a windows machine to test it this night. Please wait for a while.

**Comment by csukuangfj** [comment]
@shushanxingzhe 
Could you please try it again? It should fix the issue, I think.

**Comment by shushanxingzhe** [comment]
Very thanks for your great work! The problem have solved.
